# Generated by Django 3.0.2 on 2020-03-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_auto_20200324_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
